### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by hhy150** [zhangzhao219/WSDM-Cup-2024#2]
非常感谢代码开源！
这里有几个问题不是很理解，想询问一下：
1、模型训练：想请问下这部分微调数据集的大致格式是如何的呢？
2、Emsemble：这里是利用了不同的大语言模型嘛？我看代码主要使用SOLAR-10.7B-Instruct 模型，是用了一个模型嘛，那么是什么不同做的融合呢？

**Comment by zhangzhao219** [comment]
1. 模型训练数据格式：按照history、question、document拼接在一起，具体细节可以参考 data/wsdm/model 和 data/wsdm/prepare的差异
2. 都是 SOLAR-10.7B-Instruct 模型，融合了不同的LoRA权重推理出来的结果

**Comment by hhy150** [comment]
get了，非常感谢回复！
